replicaCount: 1

envVars:
  portvar: PORT
  portvalue: 8085

image:
  repository: rotemmadar/nodejs-web-app
  pullPolicy: IfNotPresent
  tag: "28"

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: true
  className: "nginx" # Adjust based on your cluster's ingress controller
  annotations: {}
    # Example annotations you might uncomment later:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: my-web-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Parameterizing probes allows the chart to be reused for different apps
probes:
  liveness:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
